-- 코드를 입력하세요
DELIMITER $$
CREATE PROCEDURE myFunction()
BEGIN
    DECLARE I INT DEFAULT 0;
    WHILE (i < MIN(HOUR(DATETIME))) DO
        INSERT INTO NEW_ANIMAL_OUTS VALUE(0, 0);
        SET i = i + 1;
    END WHILE;
END$$
DELIMITER ;

SELECT HOUR(DATETIME),
    CASE
    WHEN COUNT(ANIMAL_ID) = 0 THEN 0
    ELSE COUNT(ANIMAL_ID)
    END
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);